config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get '/riddle', to: 'riddles#show'
  get '/game', to: 'game#index'
  get '/game/over', to: 'game#over'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat_pic.rb
class CatPic < ApplicationRecord
end

app/models/riddle.rb
class Riddle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
    # This is a very simple game.  The game is to guess which of the 1000 numbers is the 1.
    session[:click_counter] ||= 0
    @click_counter = session[:click_counter]
    @game_array = session[:game_array]
    if params[:btn]
      if params[:btn] == '0'
        session[:click_counter] += 1
        render :index
      else
        redirect_to '/game/over'
      end
    else
      session[:click_counter] = 0
      session[:game_array] = Array.new(990, 0)
      10.times do 
        session[:game_array].insert(rand(0..989), 1)
      end
    end
  end

  def over

  end
end

app/controllers/riddles_controller.rb
class RiddlesController < ApplicationController
  def show
    @riddle = Riddle.all.sample
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/game/index.html.erb
<style>
  .button-container {
    display: flex;
    flex-wrap: wrap;
    max-width: auto; /* Adjust the maximum width as needed */
    margin: 0 auto; /* To center the buttons */
  }
  .game-info {
    text-align: center;
  }

  .guess-info {
    text-align: center;
  }

  form {
    margin: 5px; /* Adjust the margin to add spacing between buttons */
  }

  .go_home_btn {
    text-align: center;
  }
</style>

<div class="go_home_btn">
  <%= button_to "Go Home", root_path, method: :get %>
</div>

<h1 class="game-info">Find the correct button, that is all.</h1>
<h2 class="guess-info">You have made <%= @click_counter %> guesses</h2>

<div class="button-container">
  <% @game_array.each do |btn| %>
    <%= form_with url: game_path, method: :get, local: true do |f| %>
      <%= f.hidden_field :btn, value: btn %>
      <%= f.submit "Click Me" %>
    <% end %>   
  <% end %>
</div>

app/views/game/over.html.erb
<style>
@keyframes winAnimation {
  0% { transform: rotate(0deg) scale(1); opacity: 1; }
  50% { transform: rotate(360deg) scale(1.5); opacity: 0.8; }
  100% { transform: rotate(720deg) scale(2); opacity: 0.5; }
}

.you-win {
  text-align: center;
  font-size: 100px;
  font-weight: bold;
  color: #ff0000;
  text-transform: uppercase;
  animation: winAnimation 2s infinite;
}
  @keyframes confettiAnimation {
    0% {
      transform: rotate(45deg) translate3D(0, 0, 0);
    }
    100% {
      transform: rotate(45deg) translate3D(-2000px, 2000px, 0);
    }
  }

.confetti-container {
  position: relative;
  overflow: hidden;
  width: 100%;
  height: 100%;
  z-index: 1;
}

.confetti {
  position: absolute;
  width: 10px;
  height: 10px;
  border-radius: 50%;
  opacity: 0.8;
  transform: rotate(45deg);
  animation: confettiAnimation 2s infinite;
}
</style>
<div class="confetti-container">
  <h1 class="you-win">You Win!!</h1>
</div>
<script>
  createConfetti();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FateScraper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/riddles/show.html.erb
<style>
  .body {
    text-align: center;
    font-size: 12px;
  }
  .title {
    text-align: center;
    font-size: 25px;
  }

  .question {
    text-align: center;
    font-size: 15px;
  }

  .answer {
    color: transparent;
    text-align: center;
    font-size: 30px;
    border: 10px solid black;
    right-margin: 100px;
    left-margin: 100px;
  }

  .answer:hover {
    color: black;
  }
</style>

<body class="body">
<br>
<br>
<br>
  <div class="title">
    <h1><%= @riddle.title %>:</h1>
  </div>
  <br>
  <br>
  <div class="question">
    <h2><%= @riddle.question %></h2>
  </div>
  <br>
  <br>
  <br>
  <h3>Hover your courser over the box below to reveal the answer.</h3>
  <br>
  <div class="answer">
    <%= @riddle.answer %>
  </div>
  <br>
  <div class="new_riddle_btn">
    <%= button_to "Click here to genreate a new riddle.", riddle_path, method: :get %>
  </div>
  <br>
  <div class="go_home_btn">
    <%= button_to "Go Home", root_path, method: :get %>
  </div>
</body>

app/views/welcome/index.html.erb
<style>
  .body {
    text-align: center;
  }
</style>

<body class="body">
<br>
<br>
<br>
<br>
<br>
  <h1>Welcome, prepare to seal your fate. Choose your challenge.</h1>
  <br>
  <br>
  <br>
  <section class="btn_section">
    <div class="riddle_btn">
      <%= button_to "Solve a Riddle!", riddle_path, method: :get %>
        <div class="desc_of_riddle_game">
        <h3>
          You will be given a riddle to solve. If you solve it, you win! Simple as that!
        </h3>
      </div>
    </div>
    <br>
    <br>
    <div class="game_btn">
      <%= button_to "Play a Game", game_path, method: :get %>
      <div class="desc_of_game">
        <h3>
          You will have the chance to play a weird game... Good luck!
        </h3>
      </div>
    </div>
  </section>
</body>